version: '1'
services:
  nginx:
    container_name: nginx-container
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart:
      - always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: $HOME/inception/srcs/requirements/wordpress/tools/srcs

